### PR TITLE
refactor subscriber type to an interface instead of a function

### PR DESCRIPTION
**Pull request by haikoschol**
Another refactoring, changing subscribers to be structs that implement an interface instead of just a function. The main reason I used a function initially was to avoid the second layer of dispatching in the individual message handlers and to avoid having to allocate a struct for every subscriber. But that doesn't work for identifying network clients since the function they subscribe with will always be the same. It would be possible to pass a struct and a function when subscribing, to avoid the extra `switch` in `HandleMessage()`. But after implementing it with the `switch` I think it's fine as it is, since `HandleMessage()` contains some setup code that was in the specific handlers before, making the latter shorter.

### CODE REVIEW

**Comment by haikoschol** [comment]
@bkchr Yeah that is not very nice. The reason is that `HandleMessage` is called by the broker, which is in its own package. The `devices` package and its subpackages contain business logic, whereas `mqtt` is supposed to be unaware of that. Maybe that generalization is not very useful. :thinking:

**Comment by bkchr** [comment]
But isn't `ParseTopic``mqtt`specific? The function does not contain any business logic? Couldn't the broker implement the `ParseTopic` function?

**Comment by haikoschol** [comment]
It has `DeviceName`, which is specific to how we structure topics. What bugs me more about `HandleMessage` is using `interface{}` for the message payload. But I can't think of a way to improve that, even with moving some domain specific stuff into the broker. I'll leave it as is for now. There's always another refactoring down the road. :)

**Comment by bkchr** [comment]
Okay :)

**Pull request merged**
